server:
  port: 8080

spring:
  application:
    name: user_service #Service name
  data:
    mongodb: #MongoDB connection
      database: ${env.MONGO_DATABASE}
      uri: mongodb+srv://${env.MONGO_USERNAME}:${env.MONGO_PASSWORD}@${env.MONGO_CLUSTER}
aws:
  accessKeyId: ${env.ACCESS_KEY_ID}
  secretAccessKey: ${env.SECRET_ACCESS_KEY}
  region: ${env.REGION}
  jwtSecretKeyName: ${env.JWT_SECRET_KEY_NAME}
